import React from "react";
import Link from "next/link";

type Props = {};

const Footer = (props: Props) => {
  return (
    <section className="footer">
      <div className="divider" />

      <div className="footer-container">
        <div className="headline">
          <h5>CF</h5>
          <p>
            This website is a curated collection of typefaces that are available
            under a variety of free licences somewhere on the interwebs.
          </p>
        </div>

        <div className="links-container">
          <p>All typefaces</p>
          <div>
            <Link href={""}>Cursive</Link>
            <Link href={""}>Display</Link>
            <Link href={""}>Monospace</Link>
            <Link href={""}>Sans Serif</Link>
            <Link href={""}>Serif</Link>
            <Link href={""}>Slab</Link>
          </div>
        </div>
      </div>

      <div className="divider divider-2" />

      <div className="copyright">
        <p>
          Website by{" "}
          <Link target="_blank" href="https://www.mandjoudama.com">
            Mozart On Web
          </Link>
        </p>
        <p>
          Set in <Link href="">Manrope</Link>
        </p>
        <p>
          Images generated by{" "}
          <Link target="_blank" href="">
            MidJourney
          </Link>
        </p>
      </div>
    </section>
  );
};

export default Footer;
